apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: <project_ref>
  namespace: <project_namespace>
spec:
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  instances: 1
  storage:
    size: 1Gi
