apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: <project_ref>-ingress
  namespace: baas
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`{{ .ProjectHost }}`)
      services:
        - name: "{{ .ProjectDBServiceName }}"
          port: 5432
  tls:
    secretName: "{{ .TLSSecretName }}"
