apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: <project_ref>-ingress
  namespace: baas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`<project_ref>.<baas_domain>`) && PathPrefix(`/api/auth`)
      services:
        - name: <project_ref>-api-service
          port: 5432
  tls:
    secretName: baas-wildcard-tls
