apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: <project_ref>
  namespace: <project_namespace>
spec:
  name: app
  cluster:
    name: <project_ref>
  schemas:
    - name: api
      owner: app
    - name: auth
      owner: app
    - name: dbo
      owner: app
    - name: storage
      owner: app
  extensions:
    - name: uuid-ossp
    - name: pgcrypto
    - name: citext
