-- create schemas

CREATE SCHEMA auth;
CREATE SCHEMA dbo;
CREATE SCHEMA api;
CREATE SCHEMA storage;

-- CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
